
    create table tb_users (
        user_id bigint generated by default as identity,
        user_name varchar(255),
        primary key (user_id)
    );

    alter table if exists tb_users 
       add column user_age integer;

    create table tb_posts (
        post_id bigint generated by default as identity,
        post_content varchar(1000) not null,
        post_user_id bigint,
        primary key (post_id)
    );

    alter table if exists tb_users 
       add column user_email varchar(100);

    alter table if exists tb_posts 
       add constraint FKb1nw2nf6hcnfq2ghq05jdogpn 
       foreign key (post_user_id) 
       references tb_users;

    alter table if exists tb_posts 
       add column post_like boolean;
